"""Initial Migration

Revision ID: 18248327899b
Revises: 415de2c85673
Create Date: 2019-09-25 11:22:52.982940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18248327899b'
down_revision = '415de2c85673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('pitche_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitche_id'], ['pitches.pitch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
